name: agroz_ai
description: Agroz AI — O'zbekiston dehqon, fermer va chorvadorlari uchun agro-platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # HTTP
  dio: ^5.8.0+1

  # Image
  cached_network_image: ^3.4.1

  # Image picker
  image_picker: ^1.1.2

  # Geolocation
  geolocator: ^13.0.2
  permission_handler: ^11.3.1

  # URL launcher
  url_launcher: ^6.3.1

  # Local storage
  shared_preferences: ^2.3.5

  # UI
  shimmer: ^3.0.0

  # Intl
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
